name: build3

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit Hash'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string
      UPDATE_TDLIB:
        description: 'UPDATE_TDLIB'
        required: true
        type: string
        default: 'false'
        
jobs:
  build3:
    runs-on: ubuntu-22.04
    steps:   
      - name: Parse Inputs in GITHUB_ENV
        run: |
          echo "commit_hash=${{ inputs.commit_hash }}" >> $GITHUB_ENV
          echo "version=${{ inputs.version }}" >> $GITHUB_ENV
          echo "UPDATE_TDLIB=${{ inputs.UPDATE_TDLIB }}" >> $GITHUB_ENV
          
      - name: Create Zip Files Build 3
        if: env.UPDATE_TDLIB == 'true'
        run: |
          mkdir artifacts && ARTIFACT_DIR="${PWD}/artifacts"
          echo "ARTIFACT_DIR=$ARTIFACT_DIR" >> $GITHUB_ENV
          
          wget -O "$ARTIFACT_DIR/build3_01.zip" https://zlib.net/fossils/zlib-1.3.1.tar.gz
          wget -O "$ARTIFACT_DIR/build3_02.zip" https://zlib.net/fossils/zlib-1.3.1.tar.gz
          wget -O "$ARTIFACT_DIR/build3_03.zip" https://zlib.net/fossils/zlib-1.3.1.tar.gz

      - name: Upload To Artifacts Dir
        if: env.UPDATE_TDLIB == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: ArtifactsDir
          path: ${{ env.ARTIFACT_DIR }}/*.zip
          retention-days: 1          
