# This is a basic workflow to help you get started with Actions

name: tdlib-build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-android:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: clone TD lib and compare versions
        run: |
          git clone https://github.com/s-em-i/TDLib_Flutter_client_prebuilt_binaries.git
          cd TDLib_Flutter_client_prebuilt_binaries
          LatestPrebuiltReleasedVersionTag=$(git describe --tags --abbrev=0 | sed 's/v//')
          echo $LatestPrebuiltReleasedVersionTag
          cd -
          git clone https://github.com/tdlib/td.git
          cd td
          LastReleasedVersionTag=$(git log -n 1 --grep="Update version to " --oneline)
          commit_hash=$(echo "$LastReleasedVersionTag" | awk '{print $1}')
          version=$(echo "$LastReleasedVersionTag" | grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+\.' | sed 's/\.$//')
          echo "$version"
          cd -

          echo "UPDATE_TDLIB=false" >> $GITHUB_ENV

          if [[ $(echo -e "$version\n$LatestPrebuiltReleasedVersionTag" | sort -V | head -n1) == "$LatestPrebuiltReleasedVersionTag" ]]; then
            echo "version=$version" >> $GITHUB_ENV
            echo "commit_hash=$commit_hash" >> $GITHUB_ENV
            echo "commit_message=$commit_hash Update version to $version" >> $GITHUB_ENV
            echo "UPDATE_TDLIB=true" >> $GITHUB_ENV
          fi
      
      - name: JSON to variables
        if: env.UPDATE_TDLIB == 'true'
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/td-version.json'
          prefix: tdbuild_versions
          
      - name: Upload to Telegram
        if: env.UPDATE_TDLIB == 'true'
        env:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          SESSION: ${{ secrets.TELEGRAM_SESSION }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          COMMIT_MESSAGE: ${{ env.commit_message }}
        run: |
          TDLIB_ANDROID=td/example/android/tdlib/tdlib-debug.zip
          wget ﻿﻿https://core.telegram.org/tdlib/tdlib.zip
          wget ﻿﻿https://core.telegram.org/tdlib/tdlib.zip
          TDLIB_ANDROID=tdlib.zip
          TDLIB_ANDROID2=tdlib.zig.1
          if [ ! -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
            pip3 install Telethon==${{ env.tdbuild_versions_Telethon }}
            python3 .github/workflows/tguploadbot.py $TDLIB_ANDROID $TDLIB_ANDROID2
          fi
          echo "UPDATE_TDLIB=false" >> $GITHUB_ENV

      - name: install build essentials
        if: env.UPDATE_TDLIB == 'true'
        run: |
          sudo apt-get install -y make zlib1g-dev libssl-dev gperf cmake clang libc++-dev libc++abi-dev ninja-build

      - name: Setup Android SDK
        if: env.UPDATE_TDLIB == 'true'
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: false

      - name: Install NDK and CMake
        if: env.UPDATE_TDLIB == 'true'
        run: |
          echo "=== Installing NDK ${{ env.tdbuild_versions_NDK }} ==="
          sdkmanager "ndk;${{ env.tdbuild_versions_NDK }}"
          echo "ANDROID_NDK_VERSION=${{ env.tdbuild_versions_NDK }}" >> $GITHUB_ENV
          
          echo "=== Installing CMake ${{ env.tdbuild_versions_cmake }} ==="
          sdkmanager "cmake;${{ env.tdbuild_versions_cmake }}"
          
          echo "=== Installing Android ${{ env.tdbuild_versions_platform }} Platform ==="
          sdkmanager "platforms;android-${{ env.tdbuild_versions_platform }}"
          sdkmanager "build-tools;${{ env.tdbuild_versions_build-tools }}"          
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
      
      - name: build openssl
        if: env.UPDATE_TDLIB == 'true'
        run: |
          ANDROID_SDK_ROOT=$ANDROID_HOME
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV       
          OPENSSL_INSTALL_DIR="third-party/openssl"
          OPENSSL_VERSION=${{ env.tdbuild_versions_openssl }}
          echo "OPENSSL_INSTALL_DIR=$OPENSSL_INSTALL_DIR" >> $GITHUB_ENV
          echo "OPENSSL_VERSION=$OPENSSL_VERSION" >> $GITHUB_ENV
          cd td/example/android/
          echo "./check-environment.sh"
          ./check-environment.sh
          ./build-openssl.sh $ANDROID_SDK_ROOT $ANDROID_NDK_VERSION $OPENSSL_INSTALL_DIR openssl-$OPENSSL_VERSION

      - name: build tdlib
        if: env.UPDATE_TDLIB == 'true'
        run: |
          cd td/example/android/
          ./build-tdlib.sh $ANDROID_SDK_ROOT $ANDROID_NDK_VERSION '' '' 'JSON'


