name: upload_artifacts

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit Hash'
        required: true
        type: string
      version:
        description: 'Version'
        required: true
        type: string
      UPDATE_TDLIB:
        description: 'UPDATE_TDLIB'
        required: true
        type: string
        default: 'false'
      RUN_IDS:
        description: 'RUN_IDS'
        required: true
        type: string
        
jobs:
  upload_artifacts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4    
      - name: Parse Inputs in GITHUB_ENV
        run: |
          echo "commit_hash=${{ inputs.commit_hash }}" >> $GITHUB_ENV
          echo "version=${{ inputs.version }}" >> $GITHUB_ENV
          echo "UPDATE_TDLIB=${{ inputs.UPDATE_TDLIB }}" >> $GITHUB_ENV
          echo "RUN_IDS=${{ inputs.RUN_IDS }}" >> $GITHUB_ENV
          printf "commit_message<<EOF\n%s\n%s\nEOF\n" "TDLib Prebuilt Binaries ${{ inputs.version }}" "${{ inputs.commit_hash }} Update version to ${{ inputs.version }}" >> $GITHUB_ENV
      
      - name: JSON to variables
        if: env.UPDATE_TDLIB == 'true'
        uses: rgarcia-phi/json-to-variables@v1.1.0
        with:
          filename: '.github/workflows/td-version.json'
          prefix: tdbuild_versions
          
      - name: Download Artifacts per Run-ID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=',' read -ra RUN_ID_ARRAY <<< "$RUN_IDS"
          echo "Processed Run-IDs: ${RUN_ID_ARRAY[*]}"
          
          mkdir -p artifacts
          
          wait_for_run() {
            local RUN_ID=$1
            local MAX_WAIT=1800
            local POLL_INTERVAL=30
            local ELAPSED=0
            
            while [ $ELAPSED -lt $MAX_WAIT ]; do
              STATUS=$(gh run view "$RUN_ID" --json=status,conclusion --jq '.status + " " + (.conclusion // "null")' 2>/dev/null || echo "error invalid_id")
              
              if [[ $STATUS == "completed success" ]]; then
                echo "Run $RUN_ID: Completed successfully!"
                return 0
              elif [[ $STATUS == "completed failure" ]]; then
                echo "Run $RUN_ID: Failed!"
                return 1
              elif [[ $STATUS == "completed "* ]]; then
                echo "Run $RUN_ID: Completed with neutral outcome."
                return 0
              elif [[ $STATUS == "error invalid_id" ]]; then
                echo "Run $RUN_ID: Skipping invalid ID (e.g. null)."
                return 0
              else
                echo "Run $RUN_ID: Still $STATUS. Waiting..."
              fi
              
              sleep $POLL_INTERVAL
              ELAPSED=$((ELAPSED + POLL_INTERVAL))
            done
            
            echo "Timeout waiting for Run $RUN_ID"
            return 1
          }
          
          ALL_SUCCESS=true
          for RUN_ID in "${RUN_ID_ARRAY[@]}"; do
            if [ "$RUN_ID" = "null" ] || [ -z "$RUN_ID" ]; then
              echo "Skipping invalid Run-ID: '$RUN_ID'"
              continue
            fi
            if ! wait_for_run "$RUN_ID"; then
              echo "One or more runs failed. Aborting."
              ALL_SUCCESS=false
              break
            fi
          done
          
          if [ "$ALL_SUCCESS" != true ]; then
            exit 1
          fi
          
          echo "All valid runs completed successfully. Downloading artifacts..."
          
          ZIP_COUNT=0
          for RUN_ID in "${RUN_ID_ARRAY[@]}"; do
            if [ "$RUN_ID" = "null" ] || [ -z "$RUN_ID" ]; then
              echo "Skipping invalid Run-ID for download: '$RUN_ID'"
              continue
            fi
            
            echo "Downloading from run $RUN_ID"
            
            API_RESPONSE=$(gh api \
              "/repos/${{ github.repository }}/actions/runs/$RUN_ID/artifacts" \
              --jq '{total: .total_count, artifacts: [.artifacts[] | {name: .name, url: .archive_download_url}]}' \
              --header 'Accept:application/vnd.github.v3+json' 2>/dev/null || echo '{"total":0,"artifacts":[]}')
            
            echo "API Response for Run $RUN_ID: $API_RESPONSE"
            
            TOTAL_ARTIFACTS=$(echo "$API_RESPONSE" | jq -r '.total // 0')
            if [ "$TOTAL_ARTIFACTS" -eq 0 ]; then
              echo "No artifacts for Run $RUN_ID!"
              continue
            fi
            
            ARTIFACT_URL=$(echo "$API_RESPONSE" | jq -r '.artifacts[] | select(.name == "ArtifactsDir") | .url // empty')
            ARTIFACT_NAME=$(echo "$API_RESPONSE" | jq -r '.artifacts[] | select(.name == "ArtifactsDir") | .name // empty')
            
            if [ ! -z "$ARTIFACT_URL" ]; then
              echo "Found '$ARTIFACT_NAME' - Downloading: $ARTIFACT_URL"
              if curl -L -H "Authorization: token $GITHUB_TOKEN" "$ARTIFACT_URL" -o /tmp/artifact.zip --fail --silent --show-error; then
                echo "Download success! Extracting..."
                unzip -q -j /tmp/artifact.zip -d artifacts/
                rm /tmp/artifact.zip
                
                NEW_ZIPS=$(ls artifacts/*.zip 2>/dev/null | wc -l || echo 0)
                ZIP_COUNT=$((ZIP_COUNT + NEW_ZIPS))
                echo "Extracted! New ZIPs: $NEW_ZIPS (Total: $ZIP_COUNT)"
                
                echo "Contents of artifacts/:"
                ls -la artifacts/
              else
                echo "Download failed for Run $RUN_ID (curl error: $?)"
              fi
            else
              echo "No 'ArtifactsDir' for Run $RUN_ID!"
              FALLBACK_URL=$(echo "$API_RESPONSE" | jq -r '.artifacts[0].url // empty')
              FALLBACK_NAME=$(echo "$API_RESPONSE" | jq -r '.artifacts[0].name // empty')
              if [ ! -z "$FALLBACK_URL" ]; then
                echo "Fallback: Downloading first artifact '$FALLBACK_NAME': $FALLBACK_URL"
                if curl -L -H "Authorization: token $GITHUB_TOKEN" "$FALLBACK_URL" -o /tmp/artifact.zip --fail --silent --show-error; then
                  echo "Fallback download success! Extracting..."
                  unzip -q -j /tmp/artifact.zip -d artifacts/
                  rm /tmp/artifact.zip
                  
                  NEW_ZIPS=$(ls artifacts/*.zip 2>/dev/null | wc -l || echo 0)
                  ZIP_COUNT=$((ZIP_COUNT + NEW_ZIPS))
                  echo "Fallback extracted! New ZIPs: $NEW_ZIPS (Total: $ZIP_COUNT)"
                  
                  echo "Contents of artifacts/:"
                  ls -la artifacts/
                else
                  echo "Fallback download failed for Run $RUN_ID (curl error: $?)"
                fi
              fi
            fi
          done
          
          echo "Final ZIP count: $ZIP_COUNT"
          if [ $ZIP_COUNT -eq 0 ]; then
            echo "WARNING: No ZIPs downloaded! Check builds and API response above."
          fi
          ls -la artifacts/*.zip 2>/dev/null || echo "No ZIPs present."

      - name: Upload to Telegram
        if: env.UPDATE_TDLIB == 'true'
        env:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          SESSION: ${{ secrets.TELEGRAM_SESSION }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          MESSAGE_THREAD_ID: ${{ secrets.MESSAGE_THREAD_ID }}
          COMMIT_MESSAGE: ${{ env.commit_message }}
        run: |
          if [ ! -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then
            pip3 install Telethon==${{ env.tdbuild_versions_Telethon }}
            TGUPLOAD="${PWD}/.github/workflows/tguploadbot.py"            
            cd artifacts && TG_UPLOAD_FILES=$(ls *.zip)
            python3 $TGUPLOAD $TG_UPLOAD_FILES
          fi
